# Generated by Django 5.0.3 on 2024-04-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_postmodel_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='title',
            new_name='titletext',
        ),
    ]
