# Generated by Django 5.0.3 on 2024-04-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_title_postmodel_titletext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='titletext',
            new_name='title',
        ),
    ]
